// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANkanQ9HJ1BtKc8nBkd70hRaIW3PWfwKU',
    appId: '1:483552581279:web:281e00a0b62aed39bdb4aa',
    messagingSenderId: '483552581279',
    projectId: 'gnala-cosmetic',
    authDomain: 'gnala-cosmetic.firebaseapp.com',
    storageBucket: 'gnala-cosmetic.firebasestorage.app',
    databaseURL: 'https://gnala-cosmetic-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnuhFsXzhdvYD2x8AC0E66sDZISM5IqVE',
    appId: '1:483552581279:android:5547cd5ba1348550bdb4aa',
    messagingSenderId: '483552581279',
    projectId: 'gnala-cosmetic',
    storageBucket: 'gnala-cosmetic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXQW6Y8vwnWhlyunWlvyFymPDIjB0p0XA',
    appId: '1:483552581279:ios:a6753ec4beb60476bdb4aa',
    messagingSenderId: '483552581279',
    projectId: 'gnala-cosmetic',
    storageBucket: 'gnala-cosmetic.firebasestorage.app',
    iosBundleId: 'com.example.gnalaCosmetic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopment123456789',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'gnala-cosmetic',
    storageBucket: 'gnala-cosmetic.appspot.com',
    iosBundleId: 'com.example.gnalaCosmetic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForDevelopment123456789',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'gnala-cosmetic',
    authDomain: 'gnala-cosmetic.firebaseapp.com',
    storageBucket: 'gnala-cosmetic.appspot.com',
  );
}








